version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    # Auto-merge patch and minor updates only
    # Major updates will require manual review (no auto-merge by default)
    enable-auto-merge: true