name: Lighthouse CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write # Allow posting PR comments

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Audit URLs with Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://slopsauce.github.io/QRetro/
            https://slopsauce.github.io/QRetro/share
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: .github/lighthouse/budget.json
          configPath: .github/lighthouse/lighthouserc.json